# Generated by Django 4.2.21 on 2025-11-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0014_alter_ocrcachehit_result_ids"),
        ("ocr", "0014_remove_ocrresult_confidence_ocrcache_is_verified_and_more"),
    ]

    operations = []
