# Generated by Django 4.2.21 on 2025-11-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0015_merge_20251127_1108"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrresult",
            name="corrected_origin_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="人工矫正来源ID"
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="是否人工校验"),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="result_type",
            field=models.IntegerField(
                choices=[(1, "正确"), (2, "误检"), (3, "漏检")],
                default=1,
                verbose_name="识别结果类型",
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="ocr.ocrtask",
                verbose_name="所属任务",
            ),
        ),
    ]
