# Generated by Django 4.2.21 on 2025-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0016_ocrresult_corrected_origin_id_ocrresult_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrtask",
            name="verified_images",
            field=models.IntegerField(default=0, verbose_name="已校验图片数"),
        ),
    ]
