# Generated by Django 4.1 on 2025-12-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0017_ocrtask_verified_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrproject",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="is_translated",
            field=models.BooleanField(
                default=False, null=True, verbose_name="是否已翻译"
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="trans_image_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="翻译后图片路径"
            ),
        ),
        migrations.AlterField(
            model_name="ocrresult",
            name="result_type",
            field=models.IntegerField(
                choices=[(1, "正确"), (2, "错误")],
                default=1,
                verbose_name="识别结果类型",
            ),
        ),
        migrations.AlterField(
            model_name="ocrtask",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="ocr.ocrproject",
                verbose_name="所属项目",
            ),
        ),
    ]
