# Generated by Django 4.2.21 on 2025-11-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_alter_report_success_rate"),
        ("reports", "0007_alter_report_success_rate"),
    ]

    operations = []
